### ISSUE TITLE
[Error] function: chargeBatteries -- file: ISAPowerbank_server.lua line # 132 | MOD: Immersive Solar Arrays [23.5.1]

### ISSUE THREAD

**Issue by 6--** [radx5Blue/ImmersiveSolarArrays#52]
```
-----------------------------------------
STACK TRACE
-----------------------------------------
function: chargeBatteries -- file: ISAPowerbank_server.lua line # 132 | MOD: Immersive Solar Arrays [23.5.1]
function: updatePowerbanks -- file: ISAPowerbankSystem_server.lua line # 166 | MOD: Immersive Solar Arrays [23.5.1]
LOG  : General     , 1682990190490> 79,402,591> -----------------------------------------
STACK TRACE
-----------------------------------------
function: chargeBatteries -- file: ISAPowerbank_server.lua line # 132 | MOD: Immersive Solar Arrays [23.5.1]
function: updatePowerbanks -- file: ISAPowerbankSystem_server.lua line # 166 | MOD: Immersive Solar Arrays [23.5.1]
ERROR: General     , 1682990190490> 79,402,591> ExceptionLogger.logException> Exception thrown java.lang.RuntimeException: Object tried to call nil in chargeBatteries at KahluaUtil.fail line:82.
ERROR: General     , 1682990190490> 79,402,591> DebugLogStream.printException> Stack trace:
java.lang.RuntimeException: Object tried to call nil in chargeBatteries
	at se.krka.kahlua.vm.KahluaUtil.fail(KahluaUtil.java:82)
	at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:973)
	at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
	at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
	at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
	at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
	at zombie.Lua.Event.trigger(Event.java:64)
	at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:65)
	at zombie.GameTime.update(GameTime.java:671)
	at zombie.gameStates.IngameState.UpdateStuff(IngameState.java:566)
	at zombie.gameStates.IngameState.updateInternal(IngameState.java:1623)
	at zombie.gameStates.IngameState.update(IngameState.java:1333)
	at zombie.network.GameServer.main(GameServer.java:903)

```

I'm not sure whats causing this bug, i see it every 5 seconds or so
I was using github version but was using ISA id, now i was forced to switch to ISA_41

**Comment by Poltergeistzx** [comment]
When I released ISA_41, I added a warning that ISA will be removed in the future.

I hope this link helps you.

https://steamcommunity.com/workshop/filedetails/discussion/2857548524/3762229314896836679/

**Comment by 6--** [comment]
Thanks for the reply,

I just noticed your post here
https://steamcommunity.com/workshop/filedetails/discussion/2857548524/3762229314896836679/#c3823036783898362025

will add the lua file to my custom mod as you mentioned, and hopefully it fix the issue!
lua/server/myPatchesFile.lua
```
if isClient() then return end
local isa = ImmersiveSolarArrays or require("ISAUtilities")
local patchOnLoad = function(isoObject)
    local square = isoObject:getSquare()
    if not square then return end
    local container = isoObject:getContainer()
    local items = container:getItems()
    for i=items:size()-1,0,-1 do
        local item = items:get(i)
        if not (item:getModData().ISA_maxCapacity or isa.maxBatteryCapacity[item:getType()]) then
            container:Remove(item)
            square:AddWorldInventoryItem(item,0.5,0.5,0)
        end
    end
end
MapObjects.OnLoadWithSprite("solarmod_tileset_01_0", patchOnLoad, 3)
```

**Comment by 6--** [comment]
I think its working, 3 hours and no errors.

Thanks a lot!
