### ISSUE TITLE
[ERRORS] (Loading old Files) Stack Trace using mod on MP

### ISSUE THREAD

**Issue by tgstyle** [radx5Blue/ImmersiveSolarArrays#55]
Error shows up repeatedly on clients (this is from the console.txt) when connecting to a server.

STACK TRACE
-----------------------------------------
function: updateBank -- file: CPowerbankSystem.lua line # 213 | MOD: Immersive Solar Arrays [23.9.4]

ERROR: General     , 1696887424912> 0> ExceptionLogger.logException> Exception thrown java.lang.RuntimeException: attempted index: maxBatteryCapacity of non-table: null at KahluaThread.tableget line:1689.
ERROR: General     , 1696887424912> 0> DebugLogStream.printException> Stack trace:
java.lang.RuntimeException: attempted index: maxBatteryCapacity of non-table: null
	at se.krka.kahlua.vm.KahluaThread.tableget(KahluaThread.java:1689)
	at se.krka.kahlua.vm.KahluaThread.luaMainloop(KahluaThread.java:492)
	at se.krka.kahlua.vm.KahluaThread.call(KahluaThread.java:163)
	at se.krka.kahlua.vm.KahluaThread.pcall(KahluaThread.java:1980)
	at se.krka.kahlua.vm.KahluaThread.pcallvoid(KahluaThread.java:1812)
	at se.krka.kahlua.integration.LuaCaller.pcallvoid(LuaCaller.java:66)
	at se.krka.kahlua.integration.LuaCaller.protectedCallVoid(LuaCaller.java:139)
	at zombie.Lua.Event.trigger(Event.java:64)
	at zombie.Lua.LuaEventManager.triggerEvent(LuaEventManager.java:65)
	at zombie.GameTime.update(GameTime.java:671)
	at zombie.gameStates.IngameState.UpdateStuff(IngameState.java:566)
	at zombie.gameStates.IngameState.updateInternal(IngameState.java:1623)
	at zombie.gameStates.IngameState.update(IngameState.java:1333)
	at zombie.gameStates.GameStateMachine.update(GameStateMachine.java:101)
	at zombie.GameWindow.logic(GameWindow.java:298)
	at zombie.core.profiling.AbstractPerformanceProfileProbe.invokeAndMeasure(AbstractPerformanceProfileProbe.java:71)
	at zombie.GameWindow.frameStep(GameWindow.java:765)
	at zombie.GameWindow.run_ez(GameWindow.java:667)
	at zombie.GameWindow.mainThread(GameWindow.java:495)
	at java.base/java.lang.Thread.run(Unknown Source)
LOG  : General     , 1696887424913> 0> -----------------------------------------
STACK TRACE
-----------------------------------------
function: updateBank -- file: CPowerbankSystem.lua line # 213 | MOD: Immersive Solar Arrays [23.9.4]

**Comment by Poltergeistzx** [comment]
This file is no longer in the mod, please delete the mod folder and any other versions of the mod.

**Comment by Poltergeistzx** [comment]
Best way to remove old files - other versions from your mod folders is to search for the line `id=ISA_41` or another mod id that has the issue, delete that mod folder completely and unsubscribe from the mod. After it's removed, download it again.
